#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CompanyFinder.Resource", IsApplication=true)]

namespace CompanyFinder
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::CompanyFinder.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int accent = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int divider = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int primary = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int primary_dark = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int primary_light = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int primary_text = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int secondary_text = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int text = 2131034119;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int detectiveIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int findCompany = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int findWhite = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int label = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int WhiteFindCompany = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int NameLabel = 2131165193;
			
			// aapt resource value: 0x7f070022
			public const int addressLabel = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int addressText = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int addressesSection = 2131165219;
			
			// aapt resource value: 0x7f070029
			public const int countryLabel = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int countryText = 2131165226;
			
			// aapt resource value: 0x7f07001a
			public const int email1Label = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int email1Text = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int email2Label = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int email2Text = 2131165213;
			
			// aapt resource value: 0x7f070003
			public const int emailText = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int findButton = 2131165188;
			
			// aapt resource value: 0x7f07000f
			public const int foundedLabel = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int foundedText = 2131165200;
			
			// aapt resource value: 0x7f07002b
			public const int imagesSection = 2131165227;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout = 2131165186;
			
			// aapt resource value: 0x7f070017
			public const int link1Text = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int link2Text = 2131165208;
			
			// aapt resource value: 0x7f070016
			public const int linksSection = 2131165206;
			
			// aapt resource value: 0x7f070025
			public const int localityLabel = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int localityText = 2131165222;
			
			// aapt resource value: 0x7f070007
			public const int logoWebView = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int nameText = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int noResultsText = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int numEmpLabel = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int numEmpText = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int onLineLabel = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int onLineText = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int organazationSection = 2131165192;
			
			// aapt resource value: 0x7f070019
			public const int overviewText = 2131165209;
			
			// aapt resource value: 0x7f07001e
			public const int phone1Label = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int phone1Text = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int phone2Label = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int phone2Text = 2131165217;
			
			// aapt resource value: 0x7f070005
			public const int progressBar = 2131165189;
			
			// aapt resource value: 0x7f070027
			public const int regionLabel = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int regionText = 2131165224;
			
			// aapt resource value: 0x7f070006
			public const int resultView = 2131165190;
			
			// aapt resource value: 0x7f070014
			public const int social1Text = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int social2Text = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int socialProfilesSection = 2131165203;
			
			// aapt resource value: 0x7f070000
			public const int toolBar = 2131165184;
			
			// aapt resource value: 0x7f070011
			public const int websiteLabel = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int websiteText = 2131165202;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int toolBar = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int APIkey = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int APIurl = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
